import type { Metadata } from "next";
import "./globals.css";
import Header2 from "../components/mvpblocks/header-2";
import Header from "./components/header";
import { ThemeProvider } from "next-themes";
import { Providers } from "./providers";
import { SidebarDemo } from "./dashboard";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="w-full h-screen font-inter">
        <Providers>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="min-h-screen w-full relative rounded-tl-2xl overflow-hidden">
              {/* Aurora Edge Glow Background */}
              <div
                className="absolute inset-0 -z-10"
                style={{
                  background:
                    "radial-gradient(ellipse 50% 100% at 10% 0%, rgba(226, 232, 240, 0.15), transparent 65%), #ffffff",
                }}
              />
              <div
                className="absolute inset-0 -z-10 dark:block hidden"
                style={{
                  background:
                    "radial-gradient(ellipse 50% 100% at 10% 0%, rgba(226, 232, 240, 0.15), transparent 65%), oklch(0.2 0 0)",
                }}
              />
              {children}
            </div>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
